const images = {
    BackgroundImage : require('../assets/blurimage.png'),
    lock : require('../assets/lock.png'),
    logo : require('../assets/sapsnewlogo.png'),
    CountryCode : require('../assets/cc.png'),
    menu : require('../assets/menu1.png'),
    bell : require('../assets/bell1.png'),
    sapslogo : require('../assets/sapslogo.png'),
    search : require('../assets/search.png'),
    content : require('../assets/content.png'),
    createcampaign : require('../assets/createcampaign.png'),
    schedule : require('../assets/shcedule.png'),
    add : require('../assets/add.png'),
    back : require('../assets/back.png'),
    baner : require('../assets/banerbb.png'),
    star : require('../assets/Star.png'),
    map : require('../assets/map.png'),
    rback : require('../assets/rback.png'),
    play1 : require('../assets/play1.png'),
    order : require('../assets/order.png'),
    time : require('../assets/time.png'),
    baner1 : require('../assets/baner1.png'),
    line : require('../assets/line.png'),
    calender : require('../assets/calender.png'),
    clock : require('../assets/clock.png'),
    edit : require('../assets/edit.png'),
    time1 : require('../assets/time1.png'),
    cross : require('../assets/cross.png'),
    edit1 : require('../assets/edit1.png'),
    appimage : require('../assets/appimage.png'),
    eye : require('../assets/eye.png'),
    help : require('../assets/HELP.png'),
    confirmation : require('../assets/group.png'),
    mail : require('../assets/mail.png'),
    nodata : require('../assets/nothing.png'),
    plus1 : require('../assets/plus1.png'),
    board : require('../assets/board.png'),
    banerimage: require('../assets/banerbb.png'),
    calender: require('../assets/calender.png'),
    time: require('../assets/time1.png'),
    watch: require('../assets/clock.png'),
    edit: require('../assets/edit.png'),
    error : require('../assets/error.png'),
    timecolor : require('../assets/t.png'),
    eyeclosed : require('../assets/ic.png'),
    eyeopen : require('../assets/eyeopen.png'),
    campaign1 : require('../assets/campaign1.png'),
    p : require('../assets/p.png'),
    p1 : require('../assets/postadd.png'),
    bill1 : require('../assets/bill1.png'),
    settings : require('../assets/settings.png'),
    terms : require('../assets/terms.png'),
    privacy : require('../assets/privacy.png'),
    logout : require('../assets/logout.png'),
    wallet : require('../assets/wallet.png'),
    gallery1 : require('../assets/gallery1.png'),
    orders1 : require('../assets/orders1.png'),
    camp : require('../assets/camp.png'),
    pro : require('../assets/pro.png'),
    drawerlogo : require('../assets/drawerlogo.png'),
    verify : require('../assets/verify.png'),
    campBill : require('../assets/campbill.png'),
    delete : require('../assets/delete.png'),
    emptyorders : require('../assets/emptyorders.png'),
    emptybillboard : require('../assets/emptybillboard.png'),
    pin : require('../assets/mappin.png'),
    leftarrow : require('../assets/left.png'),
    sort : require('../assets/sort.png'),
    pinned : require('../assets/pinned.png'),
    logoPin : require('../assets/mapppp.png'),
    belll : require('../assets/belll.png'),
    gallerylogo : require('../assets/gallerylogo.png'),
    facebook : require('../assets/fb.png'),
    twitter : require('../assets/twitter.png'),
    linkdin : require('../assets/linkdin.png'),
    google : require('../assets/google.png'),
    logButton : require('../assets/logbutton.png'),
    SAPSLOGO : require('../assets/SAPS_Logo 3.png'),
    whiteCross : require('../assets/whitecross.png'),
    connectFb : require('../assets/connectfb.png'),
    connecttwitter : require('../assets/connecttwitter.png'),
    connectlink : require('../assets/connectlink.png'),
    publishAd : require('../assets/publishad.png'),
    brand: require('../assets/brand.png'),
    reach : require('../assets/expand.png'),
    nearme : require('../assets/nearme1.png'),
    delhi : require('../assets/delhi.png'),
    mumbai : require('../assets/mumbai.png'),
    agra : require('../assets/agra.png'),
    goa : require('../assets/goa.png'),
    indoor : require('../assets/indoor.png'),
    outdoor : require('../assets/outdoor.png'),
    highway : require('../assets/highway.png'),
    airway : require('../assets/airway.png'),
    railway : require('../assets/railway.png'),
    mall : require('../assets/mall.png'),
    subway : require('../assets/subway.png'),
    bar : require('../assets/bar.png'),
    user : require('../assets/user.png'),
    taxi : require('../assets/taxi.png'),
    graphd : require('../assets/graphd.png'),
    pie : require('../assets/pie.png'),
    heart : require('../assets/heart.png'),
    rect : require('../assets/rect.png'),
    rect1 : require('../assets/rect1.png'),
    coupan : require('../assets/coupan.png'),
    addagency : require('../assets/addmember.png'),
    profilepic: require('../assets/profilepic.png'),
    deletegroup : require('../assets/deletegroup.png'),
    contactgroup: require('../assets/contactgroup.png'),
    spend : require('../assets/spend.png'),
    reverseback : require('../assets/reverseback.png'),
    fb1: require('../assets/fb1.png'),
    l1 : require('../assets/l1.png'),
    t1 : require('../assets/t1.png'),
    fbc : require('../assets/fbc.png'),
    lc : require('../assets/lc.png'),
    tc : require('../assets/tc.png'),
    heart1 : require('../assets/heart1.png'),
    image1 : require('../assets/1.png'),
    pic1 : require('../assets/pic1.png'),
    filter : require('../assets/filter.png'),
    pma : require('../assets/pma.png'),
    redheart : require('../assets/redheart.png'),
    walletMain : require('../assets/wm.png'),
    analysis: require('../assets/analysis.png'),
    wallett: require('../assets/wallett.png'),
    wpma : require('../assets/tvv.png'),
    bigcross : require('../assets/bigcross.png'),
    coupons : require('../assets/coupons1.png'),
    checkout : require('../assets/checkout.png'),
    refund : require('../assets/refund.png'),
    rewards : require('../assets/rewards.png'),
    hh : require('../assets/hh.png'),
    chennai: require('../assets/chennai.png'),
    jaipur: require('../assets/jaipur.png'),
    saudi: require('../assets/saudi.png'),
    dubai: require('../assets/dubai.png'),
    bang: require('../assets/bang.png'),
    bhopal: require('../assets/bhopal.png'),
    pune: require('../assets/pune.png'),
    verified: require('../assets/verified.png'),
    verified1: require('../assets/verified1.png'),
    gall: require('../assets/gall.png'),
    ehh:require('../assets/ehh.png'),
    rhh: require('../assets/rhh.png'),
    bbell: require('../assets/bbell.png')



    
    
}

export default images;